### PR TITLE
[tech] Calendar entries across monthly borders

### PR DESCRIPTION
**Pull request by rleh**
Finally 🥳 

---

Seems to work, below are old.ics and new.ics compared using `git diff --no-index -I "DTSTAMP" old.ics.txt new.ics.txt`.

The changes in the generated ICS file are:
- `DTSTAMP` fields (obviously ... they contain the current time)
- some previously broken end times
- TechTurbo entries, because of 016a5f0

<details>
<summary>
Click to view diff
</summary>

[new.ics.txt](https://github.com/TechAachen/Webseite-Jekyll/files/15472950/new.ics.txt)
[old.ics.txt](https://github.com/TechAachen/Webseite-Jekyll/files/15472951/old.ics.txt)

```diff
diff --git a/old.ics b/new.ics
index eb65f61..966cc15 100644
--- a/old.ics
+++ b/new.ics
@@ -905,8 +905,8 @@ UID:meeting+20221024T083000@techaachen.de
 SUMMARY:TechAachen - Women@TechAachen - Design Thinking Workshop mit female@FIR
 LOCATION:Details bitte bei Women@TechAachen erfragen; Anmeldung erforderlich
 DTSTART;TZID=Europe/Berlin:20221024T083000
-DTEND;TZID=Europe/Berlin:20221024.7T1680.000
-DTSTAMP:20240528T000622Z
+DTEND;TZID=Europe/Berlin:20221024T170000
+DTSTAMP:20240528T160441Z
 END:VEVENT
 BEGIN:VEVENT
 UID:meeting+20221026T200000@techaachen.de
@@ -1145,24 +1145,16 @@ UID:meeting+20231130T160000@techaachen.de
 SUMMARY:TechAachen - TechTurbo 2023
 LOCATION:Gruppenunterkunft Auszeit Eifel, Auf der Batterie 9, Schleiden
 DTSTART;TZID=Europe/Berlin:20231130T160000
-DTEND;TZID=Europe/Berlin:20231131T000
-DTSTAMP:20240528T000622Z
-END:VEVENT
-BEGIN:VEVENT
-UID:meeting+20231201T000000@techaachen.de
-SUMMARY:TechAachen - TechTurbo 2023
-LOCATION:Gruppenunterkunft Auszeit Eifel, Auf der Batterie 9, Schleiden
-DTSTART;TZID=Europe/Berlin:20231201T000000
 DTEND;TZID=Europe/Berlin:20231203T140000
-DTSTAMP:20240528T000622Z
+DTSTAMP:20240528T160441Z
 END:VEVENT
 BEGIN:VEVENT
 UID:meeting+20231202T083000@techaachen.de
 SUMMARY:TechAachen - Frühstück
 LOCATION:Einstein, Gruppenunterkunft Auszeit Eifel, Auf der Batterie 9, Schleiden
 DTSTART;TZID=Europe/Berlin:20231202T083000
-DTEND;TZID=Europe/Berlin:20231202.408333335T980.000
-DTSTAMP:20240528T000622Z
+DTEND;TZID=Europe/Berlin:20231202T100000
+DTSTAMP:20240528T160441Z
 END:VEVENT
 BEGIN:VEVENT
 UID:meeting+20231202T093000@techaachen.de
@@ -1177,16 +1169,16 @@ UID:meeting+20231202T100000@techaachen.de
 SUMMARY:TechAachen - Altium Designer Workshop
 LOCATION:Raum Yousafzai, Gruppenunterkunft Auszeit Eifel, Auf der Batterie 9, Schleiden
 DTSTART;TZID=Europe/Berlin:20231202T100000
-DTEND;TZID=Europe/Berlin:20231202.520833332T1250.000
-DTSTAMP:20240528T000622Z
+DTEND;TZID=Europe/Berlin:20231202T123000
+DTSTAMP:20240528T160441Z
 END:VEVENT
 BEGIN:VEVENT
 UID:meeting+20231202T123000@techaachen.de
 SUMMARY:TechAachen - Gruppenfoto
 LOCATION:Gruppenunterkunft Auszeit Eifel, Auf der Batterie 9, Schleiden
 DTSTART;TZID=Europe/Berlin:20231202T123000
-DTEND;TZID=Europe/Berlin:20231202.533333335T1280.000
-DTSTAMP:20240528T000622Z
+DTEND;TZID=Europe/Berlin:20231202T130000
+DTSTAMP:20240528T160441Z
 END:VEVENT
 BEGIN:VEVENT
 UID:meeting+20231202T130000@techaachen.de
@@ -1201,8 +1193,8 @@ UID:meeting+20231202T153000@techaachen.de
 SUMMARY:TechAachen - FreeRTOS Workshop
 LOCATION:Curie, Gruppenunterkunft Auszeit Eifel, Auf der Batterie 9, Schleiden
 DTSTART;TZID=Europe/Berlin:20231202T153000
-DTEND;TZID=Europe/Berlin:20231202.7T1680.000
-DTSTAMP:20240528T000622Z
+DTEND;TZID=Europe/Berlin:20231202T170000
+DTSTAMP:20240528T160441Z
 END:VEVENT
 BEGIN:VEVENT
 UID:meeting+20231202T153000@techaachen.de
@@ -1217,16 +1209,16 @@ UID:meeting+20231202T173000@techaachen.de
 SUMMARY:TechAachen - KiCAD Workshop
 LOCATION:Curie, Gruppenunterkunft Auszeit Eifel, Auf der Batterie 9, Schleiden
 DTSTART;TZID=Europe/Berlin:20231202T173000
-DTEND;TZID=Europe/Berlin:20231202.783333335T1880.000
-DTSTAMP:20240528T000622Z
+DTEND;TZID=Europe/Berlin:20231202T190000
+DTSTAMP:20240528T160441Z
 END:VEVENT
 BEGIN:VEVENT
 UID:meeting+20231202T173000@techaachen.de
 SUMMARY:TechAachen - Indesign Workshop
 LOCATION:Yousafzai, Gruppenunterkunft Auszeit Eifel, Auf der Batterie 9, Schleiden
 DTSTART;TZID=Europe/Berlin:20231202T173000
-DTEND;TZID=Europe/Berlin:20231202.783333335T1880.000
-DTSTAMP:20240528T000622Z
+DTEND;TZID=Europe/Berlin:20231202T190000
+DTSTAMP:20240528T160441Z
 END:VEVENT
 BEGIN:VEVENT
 UID:meeting+20231202T210000@techaachen.de
@@ -1241,8 +1233,8 @@ UID:meeting+20231202T083000@techaachen.de
 SUMMARY:TechAachen - Frühstück
 LOCATION:Einstein, Gruppenunterkunft Auszeit Eifel, Auf der Batterie 9, Schleiden
 DTSTART;TZID=Europe/Berlin:20231202T083000
-DTEND;TZID=Europe/Berlin:20231202.408333335T980.000
-DTSTAMP:20240528T000622Z
+DTEND;TZID=Europe/Berlin:20231202T100000
+DTSTAMP:20240528T160441Z
 END:VEVENT
 BEGIN:VEVENT
 UID:meeting+20231202T130000@techaachen.de
@@ -1265,8 +1257,8 @@ UID:meeting+20231213T200000@techaachen.de
 SUMMARY:TechAachen - Geschäftsführende Versammlung
 LOCATION:Raum 2090|U203 (FT103), Melatener Str. 23-25
 DTSTART;TZID=Europe/Berlin:20231213T200000
-DTEND;TZID=Europe/Berlin:20231213.84375T2025.000
-DTSTAMP:20240528T000622Z
+DTEND;TZID=Europe/Berlin:20231213T201500
+DTSTAMP:20240528T160441Z
 END:VEVENT
 BEGIN:VEVENT
 UID:meeting+20231213T201500@techaachen.de
@@ -1473,16 +1465,8 @@ UID:meeting+20241128T180000@techaachen.de
 SUMMARY:TechAachen - TechTurbo 2024
 LOCATION:Gruppenunterkunft Auszeit Eifel, Auf der Batterie 9, Schleiden
 DTSTART;TZID=Europe/Berlin:20241128T180000
-DTEND;TZID=Europe/Berlin:20241131T000
-DTSTAMP:20240528T000622Z
-END:VEVENT
-BEGIN:VEVENT
-UID:meeting+20241201T000000@techaachen.de
-SUMMARY:TechAachen - TechTurbo 2024
-LOCATION:Gruppenunterkunft Auszeit Eifel, Auf der Batterie 9, Schleiden
-DTSTART;TZID=Europe/Berlin:20241201T000000
 DTEND;TZID=Europe/Berlin:20241201T140000
-DTSTAMP:20240528T000622Z
+DTSTAMP:20240528T160441Z
 END:VEVENT
 BEGIN:VEVENT
 UID:meeting+20241211T200000@techaachen.de
```

</details>

### CODE REVIEW

**Comment by rleh** [comment]
Supersedes #84

**Comment by rleh** [comment]
I checked the ICS file here https://icalendar.org/validator.html?url=https://preview.techaachen.de/attempt-fix-calendar_neu202405/techaachen-calendar.ics and there were some issues with duplicate UIDs:
*UID value is not unique, duplicate found near line [...]; Reference: [RFC 5545 3.8.4.7. Unique Identifier](http://icalendar.org/iCalendar-RFC-5545/3-8-4-7-unique-identifier.html)*

That problem is now also fixed in 9036138.

**Comment by joelsa** [comment]
Thank you very much!

I think this will fail for events spanning over New Year's Eve, into the next year, but I think that's not an issue and simplicity is preferred to handling that case.

**Comment by rleh** [comment]
> I think this will fail for events spanning over New Year's Eve, into the next year, but I think that's not an issue and simplicity is preferred to handling that case.

Nope, that actually works:
```yaml
- title: Silvester Special 80h
  datum: "2024-12-30"
  uhrzeit: "00.00h"
  dauer: 80
  ort: "Renate, Berlin"
```
translates to
```
[...]
BEGIN:VEVENT
UID:meeting+20241230T000000@techaachen.de
SUMMARY:TechAachen - Silvester Special 80h
LOCATION:Renate, Berlin
DTSTART;TZID=Europe/Berlin:20241230T000000
DTEND;TZID=Europe/Berlin:20250102T080000
DTSTAMP:20240528T193802Z
END:VEVENT
```

**Comment by rleh** [comment]
Merge?

**Review by joelsa — APPROVED** [review]

**Pull request merged**
